module.exports = {
  SWIPE_ACTIONS: {
    LIKE: 'like',
    PASS: 'pass',
    SUPERLIKE: 'superlike',
  },
  GENDERS: {
    MALE: 'male',
    FEMALE: 'female',
    NON_BINARY: 'non-binary',
    OTHER: 'other',
  },
  MESSAGE_TYPES: {
    TEXT: 'text',
    IMAGE: 'image',
    SYSTEM: 'system',
  },
  MESSAGE_CONTENT_TYPES: {
    TEXT: 'text',
    IMAGE: 'image',
    GIF: 'gif',
    STICKER: 'sticker',
  },
  REPORT_REASONS: {
    SPAM: 'spam',
    INAPPROPRIATE_CONTENT: 'inappropriate_content',
    HARASSMENT: 'harassment',
    FAKE_PROFILE: 'fake_profile',
    UNDERAGE: 'underage',
    OTHER: 'other',
  },
  REPORT_STATUS: {
    PENDING: 'pending',
    REVIEWED: 'reviewed',
    RESOLVED: 'resolved',
    DISMISSED: 'dismissed',
  },
  SUBSCRIPTION_TYPES: {
    FREE: 'free',
    PREMIUM: 'premium',
  },
  DEFAULT_PREFERENCES: {
    MIN_AGE: 18,
    MAX_AGE: 100,
    MAX_DISTANCE: 50, // kilometers
  },
  INTEREST_OPTIONS: [
    'travel',
    'music',
    'coffee',
    'photography',
    'cooking',
    'reading',
    'sports',
    'fitness',
    'gaming',
    'art',
    'yoga',
    'movies',
    'pets',
    'dancing',
    'startups',
  ],
  LIFESTYLE_OPTIONS: [
    'hiking',
    'nightlife',
    'vegan',
    'pet-lover',
    'early-bird',
    'night-owl',
    'minimalist',
    'spiritual',
    'fitness',
    'traveling',
    'family-oriented',
    'career-focused',
  ],
  DISCOVERY_SORT_OPTIONS: {
    BEST: 'best',
    NEWEST: 'newest',
  },
  DISCOVERY_SCORE_WEIGHTS: {
    INTERESTS: 40,
    LIFESTYLE: 20,
    DISTANCE: 20,
    ACTIVITY: 10,
    AGE: 10,
  },
};

